/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserResponse } from '../../models/user-response';

export interface DeactivateUserApiUsersUserIdDeactivatePatch$Params {
  user_id: string;
}

export function deactivateUserApiUsersUserIdDeactivatePatch(http: HttpClient, rootUrl: string, params: DeactivateUserApiUsersUserIdDeactivatePatch$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
  const rb = new RequestBuilder(rootUrl, deactivateUserApiUsersUserIdDeactivatePatch.PATH, 'patch');
  if (params) {
    rb.path('user_id', params.user_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserResponse>;
    })
  );
}

deactivateUserApiUsersUserIdDeactivatePatch.PATH = '/api/users/{user_id}/deactivate';
