/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserListResponse } from '../../models/user-list-response';

export interface ListUsersApiUsersGet$Params {
}

export function listUsersApiUsersGet(http: HttpClient, rootUrl: string, params?: ListUsersApiUsersGet$Params, context?: HttpContext): Observable<StrictHttpResponse<UserListResponse>> {
  const rb = new RequestBuilder(rootUrl, listUsersApiUsersGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserListResponse>;
    })
  );
}

listUsersApiUsersGet.PATH = '/api/users';
