/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApproveRequest } from '../../models/approve-request';
import { InteractionReviewResponse } from '../../models/interaction-review-response';

export interface ApproveInteractionApiInteractionsInteractionIdApprovePost$Params {
  interaction_id: string;
      body: ApproveRequest
}

export function approveInteractionApiInteractionsInteractionIdApprovePost(http: HttpClient, rootUrl: string, params: ApproveInteractionApiInteractionsInteractionIdApprovePost$Params, context?: HttpContext): Observable<StrictHttpResponse<InteractionReviewResponse>> {
  const rb = new RequestBuilder(rootUrl, approveInteractionApiInteractionsInteractionIdApprovePost.PATH, 'post');
  if (params) {
    rb.path('interaction_id', params.interaction_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InteractionReviewResponse>;
    })
  );
}

approveInteractionApiInteractionsInteractionIdApprovePost.PATH = '/api/interactions/{interaction_id}/approve';
