/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConfigureRequestTypesResponse } from '../../models/configure-request-types-response';

export interface ConfigureRequestTypesApiConfigItsmProjectsProjectKeyRequestTypesPost$Params {
  project_key: string;
}

export function configureRequestTypesApiConfigItsmProjectsProjectKeyRequestTypesPost(http: HttpClient, rootUrl: string, params: ConfigureRequestTypesApiConfigItsmProjectsProjectKeyRequestTypesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ConfigureRequestTypesResponse>> {
  const rb = new RequestBuilder(rootUrl, configureRequestTypesApiConfigItsmProjectsProjectKeyRequestTypesPost.PATH, 'post');
  if (params) {
    rb.path('project_key', params.project_key, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConfigureRequestTypesResponse>;
    })
  );
}

configureRequestTypesApiConfigItsmProjectsProjectKeyRequestTypesPost.PATH = '/api/config/itsm/projects/{project_key}/request-types';
