/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConfigureSpacesRequest } from '../../models/configure-spaces-request';
import { ConfigureSpacesResponse } from '../../models/configure-spaces-response';

export interface ConfigureSpacesApiConfigItsmProjectsProjectKeySpacesPost$Params {
  project_key: string;
      body: ConfigureSpacesRequest
}

export function configureSpacesApiConfigItsmProjectsProjectKeySpacesPost(http: HttpClient, rootUrl: string, params: ConfigureSpacesApiConfigItsmProjectsProjectKeySpacesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ConfigureSpacesResponse>> {
  const rb = new RequestBuilder(rootUrl, configureSpacesApiConfigItsmProjectsProjectKeySpacesPost.PATH, 'post');
  if (params) {
    rb.path('project_key', params.project_key, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConfigureSpacesResponse>;
    })
  );
}

configureSpacesApiConfigItsmProjectsProjectKeySpacesPost.PATH = '/api/config/itsm/projects/{project_key}/spaces';
