/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConfigureCategoriesRequest } from '../../models/configure-categories-request';
import { ConfigureCategoriesResponse } from '../../models/configure-categories-response';

export interface ConfigureCategoriesApiConfigItsmProjectsProjectKeyCategoriesPost$Params {
  project_key: string;
      body: ConfigureCategoriesRequest
}

export function configureCategoriesApiConfigItsmProjectsProjectKeyCategoriesPost(http: HttpClient, rootUrl: string, params: ConfigureCategoriesApiConfigItsmProjectsProjectKeyCategoriesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ConfigureCategoriesResponse>> {
  const rb = new RequestBuilder(rootUrl, configureCategoriesApiConfigItsmProjectsProjectKeyCategoriesPost.PATH, 'post');
  if (params) {
    rb.path('project_key', params.project_key, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConfigureCategoriesResponse>;
    })
  );
}

configureCategoriesApiConfigItsmProjectsProjectKeyCategoriesPost.PATH = '/api/config/itsm/projects/{project_key}/categories';
