/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConfluenceConnectionRequest } from '../../models/confluence-connection-request';
import { ConfluenceConnectionResponse } from '../../models/confluence-connection-response';

export interface ConfigureConfluenceConnectionApiConfigKnowledgeBasePost$Params {
      body: ConfluenceConnectionRequest
}

export function configureConfluenceConnectionApiConfigKnowledgeBasePost(http: HttpClient, rootUrl: string, params: ConfigureConfluenceConnectionApiConfigKnowledgeBasePost$Params, context?: HttpContext): Observable<StrictHttpResponse<ConfluenceConnectionResponse>> {
  const rb = new RequestBuilder(rootUrl, configureConfluenceConnectionApiConfigKnowledgeBasePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConfluenceConnectionResponse>;
    })
  );
}

configureConfluenceConnectionApiConfigKnowledgeBasePost.PATH = '/api/config/knowledge-base';
