/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjectConfigRequest } from '../../models/project-config-request';
import { ProjectConfigResponse } from '../../models/project-config-response';

export interface ConfigureProjectApiConfigItsmProjectsPost$Params {
      body: ProjectConfigRequest
}

export function configureProjectApiConfigItsmProjectsPost(http: HttpClient, rootUrl: string, params: ConfigureProjectApiConfigItsmProjectsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectConfigResponse>> {
  const rb = new RequestBuilder(rootUrl, configureProjectApiConfigItsmProjectsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProjectConfigResponse>;
    })
  );
}

configureProjectApiConfigItsmProjectsPost.PATH = '/api/config/itsm/projects';
