/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ItsmConnectionRequest } from '../../models/itsm-connection-request';
import { ItsmConnectionResponse } from '../../models/itsm-connection-response';

export interface ConfigureItsmConnectionApiConfigItsmPost$Params {
      body: ItsmConnectionRequest
}

export function configureItsmConnectionApiConfigItsmPost(http: HttpClient, rootUrl: string, params: ConfigureItsmConnectionApiConfigItsmPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ItsmConnectionResponse>> {
  const rb = new RequestBuilder(rootUrl, configureItsmConnectionApiConfigItsmPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ItsmConnectionResponse>;
    })
  );
}

configureItsmConnectionApiConfigItsmPost.PATH = '/api/config/itsm';
