/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConfigurePriorityMappingRequest } from '../../models/configure-priority-mapping-request';
import { ConfigurePriorityMappingResponse } from '../../models/configure-priority-mapping-response';

export interface ConfigurePriorityMappingApiConfigItsmProjectsProjectKeyPrioritiesPost$Params {
  project_key: string;
      body: ConfigurePriorityMappingRequest
}

export function configurePriorityMappingApiConfigItsmProjectsProjectKeyPrioritiesPost(http: HttpClient, rootUrl: string, params: ConfigurePriorityMappingApiConfigItsmProjectsProjectKeyPrioritiesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ConfigurePriorityMappingResponse>> {
  const rb = new RequestBuilder(rootUrl, configurePriorityMappingApiConfigItsmProjectsProjectKeyPrioritiesPost.PATH, 'post');
  if (params) {
    rb.path('project_key', params.project_key, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConfigurePriorityMappingResponse>;
    })
  );
}

configurePriorityMappingApiConfigItsmProjectsProjectKeyPrioritiesPost.PATH = '/api/config/itsm/projects/{project_key}/priorities';
