/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MetricsByCategoryResponse } from '../../models/metrics-by-category-response';

export interface GetMetricsByCategoryApiMetricsByCategoryGet$Params {
  project_id?: (string | null);
}

export function getMetricsByCategoryApiMetricsByCategoryGet(http: HttpClient, rootUrl: string, params?: GetMetricsByCategoryApiMetricsByCategoryGet$Params, context?: HttpContext): Observable<StrictHttpResponse<MetricsByCategoryResponse>> {
  const rb = new RequestBuilder(rootUrl, getMetricsByCategoryApiMetricsByCategoryGet.PATH, 'get');
  if (params) {
    rb.query('project_id', params.project_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MetricsByCategoryResponse>;
    })
  );
}

getMetricsByCategoryApiMetricsByCategoryGet.PATH = '/api/metrics/by-category';
