/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IndexingStatusResponse } from '../../models/indexing-status-response';

export interface GetIndexingStatusApiIndexingStatusGet$Params {
}

export function getIndexingStatusApiIndexingStatusGet(http: HttpClient, rootUrl: string, params?: GetIndexingStatusApiIndexingStatusGet$Params, context?: HttpContext): Observable<StrictHttpResponse<IndexingStatusResponse>> {
  const rb = new RequestBuilder(rootUrl, getIndexingStatusApiIndexingStatusGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IndexingStatusResponse>;
    })
  );
}

getIndexingStatusApiIndexingStatusGet.PATH = '/api/indexing/status';
