/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InteractionDetailResponse } from '../../models/interaction-detail-response';

export interface GetInteractionDetailApiInteractionsInteractionIdGet$Params {
  interaction_id: string;
}

export function getInteractionDetailApiInteractionsInteractionIdGet(http: HttpClient, rootUrl: string, params: GetInteractionDetailApiInteractionsInteractionIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<InteractionDetailResponse>> {
  const rb = new RequestBuilder(rootUrl, getInteractionDetailApiInteractionsInteractionIdGet.PATH, 'get');
  if (params) {
    rb.path('interaction_id', params.interaction_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InteractionDetailResponse>;
    })
  );
}

getInteractionDetailApiInteractionsInteractionIdGet.PATH = '/api/interactions/{interaction_id}';
