/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MetricsSummaryResponse } from '../../models/metrics-summary-response';

export interface GetMetricsSummaryApiMetricsSummaryGet$Params {
  project_id?: (string | null);
  from_date?: (string | null);
  to_date?: (string | null);
}

export function getMetricsSummaryApiMetricsSummaryGet(http: HttpClient, rootUrl: string, params?: GetMetricsSummaryApiMetricsSummaryGet$Params, context?: HttpContext): Observable<StrictHttpResponse<MetricsSummaryResponse>> {
  const rb = new RequestBuilder(rootUrl, getMetricsSummaryApiMetricsSummaryGet.PATH, 'get');
  if (params) {
    rb.query('project_id', params.project_id, {});
    rb.query('from_date', params.from_date, {});
    rb.query('to_date', params.to_date, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MetricsSummaryResponse>;
    })
  );
}

getMetricsSummaryApiMetricsSummaryGet.PATH = '/api/metrics/summary';
