/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AvailableSpacesResponse } from '../../models/available-spaces-response';

export interface ListAvailableSpacesApiConfigKnowledgeBaseSpacesAvailableGet$Params {
}

export function listAvailableSpacesApiConfigKnowledgeBaseSpacesAvailableGet(http: HttpClient, rootUrl: string, params?: ListAvailableSpacesApiConfigKnowledgeBaseSpacesAvailableGet$Params, context?: HttpContext): Observable<StrictHttpResponse<AvailableSpacesResponse>> {
  const rb = new RequestBuilder(rootUrl, listAvailableSpacesApiConfigKnowledgeBaseSpacesAvailableGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AvailableSpacesResponse>;
    })
  );
}

listAvailableSpacesApiConfigKnowledgeBaseSpacesAvailableGet.PATH = '/api/config/knowledge-base/spaces/available';
