/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InteractionListResponse } from '../../models/interaction-list-response';

export interface ListInteractionsApiInteractionsGet$Params {
  project_id?: (string | null);
  category?: (string | null);
  decision?: (string | null);
  from_date?: (string | null);
  to_date?: (string | null);
  limit?: number;
  offset?: number;
}

export function listInteractionsApiInteractionsGet(http: HttpClient, rootUrl: string, params?: ListInteractionsApiInteractionsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<InteractionListResponse>> {
  const rb = new RequestBuilder(rootUrl, listInteractionsApiInteractionsGet.PATH, 'get');
  if (params) {
    rb.query('project_id', params.project_id, {});
    rb.query('category', params.category, {});
    rb.query('decision', params.decision, {});
    rb.query('from_date', params.from_date, {});
    rb.query('to_date', params.to_date, {});
    rb.query('limit', params.limit, {});
    rb.query('offset', params.offset, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InteractionListResponse>;
    })
  );
}

listInteractionsApiInteractionsGet.PATH = '/api/interactions';
