/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjectStatusesResponse } from '../../models/project-statuses-response';

export interface ListProjectStatusesApiConfigItsmProjectsProjectKeyStatusesGet$Params {
  project_key: string;
}

export function listProjectStatusesApiConfigItsmProjectsProjectKeyStatusesGet(http: HttpClient, rootUrl: string, params: ListProjectStatusesApiConfigItsmProjectsProjectKeyStatusesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectStatusesResponse>> {
  const rb = new RequestBuilder(rootUrl, listProjectStatusesApiConfigItsmProjectsProjectKeyStatusesGet.PATH, 'get');
  if (params) {
    rb.path('project_key', params.project_key, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProjectStatusesResponse>;
    })
  );
}

listProjectStatusesApiConfigItsmProjectsProjectKeyStatusesGet.PATH = '/api/config/itsm/projects/{project_key}/statuses';
