/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FieldOptionsResponse } from '../../models/field-options-response';

export interface ListFieldOptionsApiConfigItsmFieldsFieldIdOptionsGet$Params {
  field_id: string;
}

export function listFieldOptionsApiConfigItsmFieldsFieldIdOptionsGet(http: HttpClient, rootUrl: string, params: ListFieldOptionsApiConfigItsmFieldsFieldIdOptionsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<FieldOptionsResponse>> {
  const rb = new RequestBuilder(rootUrl, listFieldOptionsApiConfigItsmFieldsFieldIdOptionsGet.PATH, 'get');
  if (params) {
    rb.path('field_id', params.field_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FieldOptionsResponse>;
    })
  );
}

listFieldOptionsApiConfigItsmFieldsFieldIdOptionsGet.PATH = '/api/config/itsm/fields/{field_id}/options';
