/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SelectFieldsResponse } from '../../models/select-fields-response';

export interface ListSelectFieldsApiConfigItsmFieldsGet$Params {
}

export function listSelectFieldsApiConfigItsmFieldsGet(http: HttpClient, rootUrl: string, params?: ListSelectFieldsApiConfigItsmFieldsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SelectFieldsResponse>> {
  const rb = new RequestBuilder(rootUrl, listSelectFieldsApiConfigItsmFieldsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SelectFieldsResponse>;
    })
  );
}

listSelectFieldsApiConfigItsmFieldsGet.PATH = '/api/config/itsm/fields';
