/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AvailableProjectsResponse } from '../../models/available-projects-response';

export interface ListAvailableProjectsApiConfigItsmProjectsAvailableGet$Params {
}

export function listAvailableProjectsApiConfigItsmProjectsAvailableGet(http: HttpClient, rootUrl: string, params?: ListAvailableProjectsApiConfigItsmProjectsAvailableGet$Params, context?: HttpContext): Observable<StrictHttpResponse<AvailableProjectsResponse>> {
  const rb = new RequestBuilder(rootUrl, listAvailableProjectsApiConfigItsmProjectsAvailableGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AvailableProjectsResponse>;
    })
  );
}

listAvailableProjectsApiConfigItsmProjectsAvailableGet.PATH = '/api/config/itsm/projects/available';
