/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CountriesResponse } from '../../models/countries-response';

export interface ListCountriesApiConfigCountriesGet$Params {
}

export function listCountriesApiConfigCountriesGet(http: HttpClient, rootUrl: string, params?: ListCountriesApiConfigCountriesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CountriesResponse>> {
  const rb = new RequestBuilder(rootUrl, listCountriesApiConfigCountriesGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CountriesResponse>;
    })
  );
}

listCountriesApiConfigCountriesGet.PATH = '/api/config/countries';
