/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OnboardProjectsRequest } from '../../models/onboard-projects-request';
import { OnboardProjectsResponse } from '../../models/onboard-projects-response';

export interface OnboardProjectsApiConfigItsmProjectsOnboardPost$Params {
      body: OnboardProjectsRequest
}

export function onboardProjectsApiConfigItsmProjectsOnboardPost(http: HttpClient, rootUrl: string, params: OnboardProjectsApiConfigItsmProjectsOnboardPost$Params, context?: HttpContext): Observable<StrictHttpResponse<OnboardProjectsResponse>> {
  const rb = new RequestBuilder(rootUrl, onboardProjectsApiConfigItsmProjectsOnboardPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OnboardProjectsResponse>;
    })
  );
}

onboardProjectsApiConfigItsmProjectsOnboardPost.PATH = '/api/config/itsm/projects/onboard';
