/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request para aprobar una interaccion en NEEDS_REVIEW, publica la respuesta tal cual esta.
 */
export interface ApproveRequest {

  /**
   * referencia logica al agente que revisa, sin FK hasta que exista M9
   */
  reviewed_by?: (string | null);
}
