/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response con la lista de proyectos disponibles en jsm, para que el admin elija (CU27).
 */
export interface AvailableProjectsResponse {

  /**
   * proyectos reales de la instancia de JSM, con su key y name
   */
  projects: Array<{
[key: string]: any;
}>;
}
