/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response con la lista de spaces disponibles en confluence, para que el admin elija (CU29).
 */
export interface AvailableSpacesResponse {

  /**
   * spaces reales de la instancia de Confluence, con su key y name
   */
  spaces: Array<{
[key: string]: any;
}>;
}
