/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Un item del desglose de metricas por categoria.
 */
export interface CategoryMetric {

  /**
   * cantidad de interacciones de esa categoria publicadas automaticamente
   */
  auto_publish_count: number;

  /**
   * porcentaje de resolucion automatica dentro de esa categoria
   */
  automatic_resolution_rate: number;

  /**
   * nombre de la categoria de soporte
   */
  category: string;

  /**
   * cantidad de interacciones de esa categoria
   */
  total_interactions: number;
}
