/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response de confirmacion del mapeo de prioridades.
 */
export interface ConfigurePriorityMappingResponse {

  /**
   * cantidad de mapeos de prioridad guardados
   */
  mappings_configured: number;

  /**
   * resultado de la operacion, 'ok' si salio bien
   */
  status: string;
}
