/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SpaceToLink } from '../models/space-to-link';

/**
 * Request para confirmar los spaces elegidos por el admin.
 */
export interface ConfigureSpacesRequest {
  spaces: Array<SpaceToLink>;
}
