/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response de confirmacion de categorias configuradas.
 */
export interface ConfigureCategoriesResponse {

  /**
   * cantidad de categorias que quedaron vinculadas al proyecto
   */
  categories_configured: number;

  /**
   * resultado de la operacion, 'ok' si salio bien
   */
  status: string;
}
