/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response de confirmacion de spaces vinculados.
 */
export interface ConfigureSpacesResponse {

  /**
   * cantidad de spaces vinculados al proyecto
   */
  spaces_configured: number;

  /**
   * resultado de la operacion, 'ok' si salio bien
   */
  status: string;
}
