/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request para confirmar las categorias elegidas por el admin para un proyecto.
 */
export interface ConfigureCategoriesRequest {

  /**
   * valores crudos de las categorias en JSM, tal cual, sin modificar
   */
  categories: Array<string>;
}
