/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response de confirmacion al configurar los tipos de solicitud de un proyecto.
 */
export interface ConfigureRequestTypesResponse {

  /**
   * cantidad de tipos de solicitud vinculados al proyecto
   */
  request_types_configured: number;

  /**
   * resultado de la operacion, 'ok' si salio bien
   */
  status: string;
}
