/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request para confirmar el mapeo de prioridades, el admin puede ajustar la sugerencia.
 */
export interface ConfigurePriorityMappingRequest {

  /**
   * nivel universal de prioridad como clave, lista de prioridades reales de JSM como valor
   */
  mapping: {
[key: string]: Array<string>;
};
}
