/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request para configurar la conexion con confluence.
 */
export interface ConfluenceConnectionRequest {

  /**
   * API token generado desde la cuenta de Atlassian
   */
  api_token: string;

  /**
   * url de la instancia de Confluence, por ejemplo https://tuempresa.atlassian.net/wiki
   */
  base_url: string;

  /**
   * email de la cuenta usada para autenticar contra la API de Confluence
   */
  user_email: string;
}
