/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response con los paises validos, para que el frontend arme el dropdown al dar de alta proyectos.
 */
export interface CountriesResponse {

  /**
   * paises del catalogo, con su code y name
   */
  countries: Array<{
[key: string]: any;
}>;
}
