/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request para escalar una interaccion directo a un humano, sin generar nada nuevo.
 */
export interface EscalateRequest {

  /**
   * motivo opcional del escalamiento
   */
  rejection_reason?: (string | null);

  /**
   * referencia logica al agente que revisa
   */
  reviewed_by?: (string | null);
}
