/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response con las opciones reales de un campo custom elegido por el admin.
 */
export interface FieldOptionsResponse {

  /**
   * valores posibles de ese campo en la instancia real de JSM
   */
  options: Array<string>;
}
