/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response con el estado del ultimo trabajo de indexacion, para el polling del dashboard (CU31).
 */
export interface IndexingStatusResponse {

  /**
   * cantidad de chunks generados hasta el momento
   */
  chunks_generated: number;

  /**
   * cantidad de documentos ya procesados
   */
  documents_processed: number;

  /**
   * detalle del error, si el trabajo fallo
   */
  error_detail?: (string | null);

  /**
   * spaces que cubrio este trabajo de indexacion
   */
  space_keys: Array<string>;

  /**
   * marca de tiempo de inicio del trabajo
   */
  started_at: string;

  /**
   * estado del trabajo, por ejemplo running, completed o failed
   */
  status: string;

  /**
   * cantidad total de documentos a procesar, si ya se conoce
   */
  total_documents?: (number | null);

  /**
   * marca de tiempo de la ultima actualizacion del trabajo
   */
  updated_at: string;
}
