/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Un item del listado paginado de interacciones.
 */
export interface InteractionListItem {

  /**
   * categoria detectada por el sistema
   */
  category: (string | null);

  /**
   * confidence_score de la respuesta generada
   */
  confidence_score: (number | null);

  /**
   * marca de tiempo de creacion de la interaccion
   */
  created_at: (string | null);

  /**
   * decision final del pipeline para esta interaccion
   */
  decision: (string | null);

  /**
   * id de la interaccion
   */
  interaction_id: string;

  /**
   * key del ticket en JSM, por ejemplo TARG-123
   */
  issue_key: string;

  /**
   * prioridad del ticket
   */
  priority: (string | null);

  /**
   * resumen del ticket original
   */
  summary: (string | null);
}
