/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InteractionListItem } from '../models/interaction-list-item';

/**
 * Respuesta del listado paginado de interacciones, para el dashboard.
 */
export interface InteractionListResponse {
  interactions: Array<InteractionListItem>;
}
