/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RetrievedChunkDetail } from '../models/retrieved-chunk-detail';

/**
 * Detalle completo de una interaccion puntual, con sus chunks recuperados, para el dashboard (TF-160).
 */
export interface InteractionDetailResponse {

  /**
   * categoria detectada por el sistema
   */
  category: (string | null);

  /**
   * fragmentos de la base de conocimiento usados como contexto
   */
  chunks: Array<RetrievedChunkDetail>;

  /**
   * confidence_score de la respuesta generada
   */
  confidence_score: (number | null);

  /**
   * marca de tiempo de creacion de la interaccion
   */
  created_at: (string | null);

  /**
   * decision final del pipeline para esta interaccion
   */
  decision: (string | null);

  /**
   * respuesta generada por el sistema
   */
  generated_response: (string | null);

  /**
   * id de la interaccion
   */
  interaction_id: string;

  /**
   * key del ticket en JSM, por ejemplo TARG-123
   */
  issue_key: string;

  /**
   * prioridad del ticket
   */
  priority: (string | null);

  /**
   * resumen del ticket original
   */
  summary: (string | null);

  /**
   * texto original del ticket, usado como input del pipeline
   */
  text_input: (string | null);
}
