/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response comun a las 3 acciones de revision (approve, regenerate, escalate).
 */
export interface InteractionReviewResponse {

  /**
   * accion final que tomo el sistema, por ejemplo AUTO_PUBLISH o ESCALATE
   */
  action_type: string;

  /**
   * resultado de la operacion, 'ok' si salio bien
   */
  status: string;
}
