/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request para configurar la conexion con JSM.
 */
export interface ItsmConnectionRequest {

  /**
   * API token generado desde la cuenta de Atlassian
   */
  api_token: string;

  /**
   * url de la instancia de JSM, por ejemplo https://tuempresa.atlassian.net
   */
  base_url: string;

  /**
   * email de la cuenta usada para autenticar contra la API de JSM
   */
  user_email: string;

  /**
   * secreto compartido para validar que los webhooks vienen de JSM
   */
  webhook_secret: string;
}
