/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response de confirmacion de la conexion con JSM.
 */
export interface ItsmConnectionResponse {

  /**
   * resultado de la operacion, 'ok' si las credenciales se validaron y guardaron
   */
  status: string;
}
