/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Resumen agregado de metricas de interacciones, para el dashboard.
 */
export interface MetricsSummaryResponse {

  /**
   * cantidad de interacciones publicadas automaticamente
   */
  auto_publish_count: number;

  /**
   * porcentaje de interacciones resueltas sin intervencion humana
   */
  automatic_resolution_rate: number;

  /**
   * promedio del confidence_score de las interacciones del periodo
   */
  avg_confidence_score: (number | null);

  /**
   * cantidad de interacciones escaladas a un agente humano
   */
  escalate_count: number;

  /**
   * cantidad de interacciones que quedaron pendientes de revision
   */
  needs_review_count: number;

  /**
   * cantidad de interacciones donde se le pidio mas informacion al usuario
   */
  request_info_count: number;

  /**
   * cantidad de tickets resueltos por el sistema
   */
  resolved_count: number;

  /**
   * cantidad de tickets resueltos por un humano fuera del sistema
   */
  resolved_externally_count: number;

  /**
   * cantidad total de interacciones procesadas en el periodo
   */
  total_interactions: number;
}
