/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoryMetric } from '../models/category-metric';

/**
 * Desglose de metricas por categoria, para el dashboard.
 */
export interface MetricsByCategoryResponse {
  categories: Array<CategoryMetric>;
}
