/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response de confirmacion del alta de proyectos.
 */
export interface OnboardProjectsResponse {

  /**
   * cantidad de proyectos creados o actualizados
   */
  projects_created: number;

  /**
   * resultado de la operacion, 'ok' si salio bien
   */
  status: string;
}
