/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectToOnboard } from '../models/project-to-onboard';

/**
 * Request para dar de alta los proyectos elegidos (CU27).
 */
export interface OnboardProjectsRequest {
  projects: Array<ProjectToOnboard>;
}
