/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response con las prioridades reales de jsm y una sugerencia automatica de mapeo.
 */
export interface PrioritiesWithSuggestionResponse {

  /**
   * prioridades reales de la instancia de JSM
   */
  priorities: Array<{
[key: string]: any;
}>;

  /**
   * mapeo sugerido de cada prioridad real a un nivel universal (Highest, High, Medium, Low)
   */
  suggestions: {
[key: string]: any;
};
}
