/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectStatusMapping } from '../models/project-status-mapping';
import { ProjectThresholds } from '../models/project-thresholds';

/**
 * Request para el endpoint POST /api/config/itsm/projects (CU26).
 */
export interface ProjectConfigRequest {
  status_mappings: Array<ProjectStatusMapping>;
  thresholds: ProjectThresholds;
}
