/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Mapeo de una categoria generica de estado ITSM a la transicion real de JSM, una fila por combinacion proyecto + estado (tabla project_config).
 */
export interface ProjectStatusMapping {

  /**
   * si el mapeo esta activo o fue desactivado por el admin
   */
  is_active?: boolean;

  /**
   * id del proyecto en la tabla project
   */
  project_id: string;

  /**
   * id del estado generico en la tabla ticket_status
   */
  status_id: string;

  /**
   * id real de la transicion de JSM que corresponde a este estado
   */
  system_action?: (string | null);
}
