/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response con los estados reales de un proyecto de jsm, para el mapeo del admin (TF-122).
 */
export interface ProjectStatusesResponse {

  /**
   * estados reales del workflow de JSM para ese proyecto, con su id y name
   */
  statuses: Array<{
[key: string]: any;
}>;
}
