/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Un proyecto elegido por el admin para dar de alta, con su pais correspondiente.
 */
export interface ProjectToOnboard {

  /**
   * key real del proyecto en JSM, por ejemplo TARG
   */
  code: string;

  /**
   * codigo de pais de la tabla country, por ejemplo AR
   */
  country_code: string;

  /**
   * idioma principal del proyecto, usado para la recuperacion de la base de conocimiento
   */
  language_code?: (string | null);

  /**
   * nombre del proyecto para mostrar en el dashboard
   */
  name: string;
}
