/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Umbrales de decision del pipeline, una fila por proyecto (columnas en la tabla project).
 */
export interface ProjectThresholds {

  /**
   * id del proyecto en la tabla project
   */
  project_id: string;

  /**
   * similarity_score minimo para que un chunk recuperado se use como contexto
   */
  similarity_threshold?: number;

  /**
   * confidence_score minimo para publicar la respuesta sin revision humana
   */
  threshold_auto_publish?: number;

  /**
   * confidence_score minimo para pedir revision humana en vez de escalar directo
   */
  threshold_needs_review?: number;
}
