/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response de confirmacion del endpoint de configuracion de proyecto.
 */
export interface ProjectConfigResponse {

  /**
   * cantidad de mapeos de estado que quedaron guardados
   */
  mappings_configured: number;

  /**
   * resultado de la operacion, 'ok' si salio bien
   */
  status: string;
}
