/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request para regenerar una interaccion rechazada (CU17).
 */
export interface RegenerateRequest {

  /**
   * motivo del rechazo, se usa para reintentar la generacion con ese contexto
   */
  rejection_reason: string;

  /**
   * referencia logica al agente que revisa
   */
  reviewed_by?: (string | null);
}
