/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Un chunk recuperado de la base de conocimiento, parte del detalle de una interaccion.
 */
export interface RetrievedChunkDetail {

  /**
   * titulo de la pagina de Confluence de donde salio el chunk
   */
  page_title: (string | null);

  /**
   * posicion del chunk en el ranking de resultados recuperados
   */
  rank_position: number;

  /**
   * score de similitud entre el chunk y la consulta del ticket
   */
  similarity_score: number;
}
