/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response con los campos custom de tipo lista de seleccion unica, para que el admin elija cual es categoria.
 */
export interface SelectFieldsResponse {

  /**
   * campos custom de JSM de tipo seleccion unica, con su id y nombre
   */
  fields: Array<{
[key: string]: any;
}>;
}
