/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Un space elegido por el admin para vincular al proyecto.
 */
export interface SpaceToLink {

  /**
   * pais al que corresponde este space, si aplica
   */
  country_code?: (string | null);

  /**
   * descripcion libre del space, para referencia del admin
   */
  description?: (string | null);

  /**
   * idioma del contenido de este space
   */
  language_code?: (string | null);

  /**
   * key real del space en Confluence, por ejemplo TA
   */
  space_key: string;
}
