/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Response de confirmacion, la indexacion corre en background.
 */
export interface StartIndexingResponse {

  /**
   * siempre 'queued', la indexacion se encola para el worker
   */
  status: string;
}
