/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request para disparar la indexacion de los spaces ya vinculados a un proyecto (CU30).
 */
export interface StartIndexingRequest {

  /**
   * keys de los spaces de Confluence a indexar
   */
  space_keys: Array<string>;
}
