/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  created_at: string;
  email: string;
  full_name: string;
  id: string;
  is_active: boolean;
  role: string;
}
